name: Build docker images

on:
  push:
    branches:
      - 'feature/server_build'
    tags:
      - 'v*.*.*'

jobs:
  build-web:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Remove unnecessary files
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set releaseversion
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push server image
      run: |
        docker build -t "ghcr.io/vashiru/ente/server:${{ env.RELEASE_VERSION }}" -f ./server/Dockerfile ./server
        docker push "ghcr.io/vashiru/ente/server:${{ env.RELEASE_VERSION }}"
